### ISSUE TITLE
Alternative date picker with range

### ISSUE THREAD

**Issue by ulde01** [sebgroup/bootstrap#281]
### Design decision 2020-03-25
![image](https://user-images.githubusercontent.com/45568194/77758002-89c0a180-7032-11ea-8155-ebd225315d23.png)

**What is this**
Another version of the date picker, for when the user has to enter a time period and you don't want two separate date pickers.

**Details**
https://designlibrary.sebgroup.com/components/date-picker/

**Component identifier**
component-datepicker

- If you develop this component, please let me know .
- Also, we would like to update the mobile behaviour of the calender component in general, please contact me if you want to work together.
- And as always, if this issue is not relevant to you, please comment and close.

Thank you!
/Ulrika

**Comment by hjalmers** [comment]
Since we're using this component: https://ng-bootstrap.github.io/#/components/datepicker/overview for angular projects with bootstrap this is something we already have support for. This kind of component that relies on javascript can't be fixed in this repository either but I've added an issue here https://github.com/sebgroup/ng-bootstrap/issues/80 to create an example for date ranges at least.
