### ISSUE TITLE
NG Bootstrap Accordion not updated with focus outline styling as in vanilla Bootstrap

### ISSUE THREAD

**Issue by martenbarkvall** [sebgroup/bootstrap#422]
For accordion, the vanilla bootstrap component includes the blue outline for selected items, but in ng-version, the outline is only visible in bottom. See attached.
<img width="909" alt="Accordion ng-bootstrap" src="https://user-images.githubusercontent.com/70143393/91041228-f48cfd80-e60f-11ea-8fb2-944c367f8a11.png">
<img width="946" alt="Accordion vanilla bootstrap" src="https://user-images.githubusercontent.com/70143393/91041234-f656c100-e60f-11ea-81c5-624a999bce94.png">

**Comment by hjalmers** [comment]
There might be a bug somewhere or perhaps it's due to an old version of the framework. The latest version actually has a different behavior that you can try out [here](https://sebgroup.github.io/ng-bootstrap/accordion), in that version there's not outline at all. In any case I'd say it's related to https://github.com/sebgroup/bootstrap/issues/367 as this is something that's added globally and not to specific elements. There's also this issue https://github.com/sebgroup/bootstrap/issues/375 which slipped past my radar so I'll close this for now as it's a duplicate.

**Comment by hjalmers** [comment]
See https://github.com/sebgroup/bootstrap/issues/375
