### ISSUE TITLE
Accessibility requirements compliant buttons question

### ISSUE THREAD

**Issue by sixskulls** [sebgroup/bootstrap#583]
Hi,

As per one of our requirements we are aiming to be compliant with upcoming Accessibility requirements with our GCM. We had an in-house accessibility person do a review and checked Google's lighthouse review - both flagged not sufficient contrast between default seb button color and default BA/Nexus grey background color.  Are there any plans regarding active and inactive buttons coloring? Any other tips to fix this, would also be appreciated.

Regards,
Lukas Skalskis

**Comment by hjalmers** [comment]
Hi @sixskulls, sorry for the late reply. This issue went passed my radar I'm afraid:( This library follows the guidelines specified by SEB Design Library [here](https://designlibrary.sebgroup.com/components/component-button) and I know the CX department is looking into adjusting the colors slightly. 

Just a small side note on accessibility and contrast values, Google lighthouse is a great tool and most of the time it's a good idea to follow the advice given. Regarding colors and contrast it's worth mentioning thought, that the contrast criteria is not always a good measurement and that you also have to consider the element you're looking at and what purpose it has.

We tend to apply text contrast criteria on elements which do not need contrast since they're not interactive, other rules apply to buttons as well. Some interesting articles on the topic:)

https://uxmovement.com/buttons/the-myths-of-color-contrast-accessibility/
https://www.w3.org/WAI/WCAG21/Understanding/non-text-contrast.html
