### ISSUE TITLE
Sync label text sizes

### ISSUE THREAD

**Issue by ulde01** [sebgroup/bootstrap#72]
See https://github.com/sebgroup/design-library/issues/2

**Comment by hjalmers** [comment]
Test

**Comment by hjalmers** [comment]
Hi @ulde01

**Comment by ulde01** [comment]
@hjalmers I would like to add todo's for Axure components as well. Then I probably should create a repo for that too, but why not? Could we look at this later this week? Thank you!

**Comment by hjalmers** [comment]
@ulde01 sure, I think that would make sense if we'd like to track issues for axure assets as well. I know there are some projects that share and handle versions of their assets using github too although I guess that's already built in axure (it's been a while since I used it myself). If not, maybe creating labels for axure in https://github.com/sebgroup/design-library would suffice as we'll never check-in anything to github unless we also use it to share the assets.
